CC = gcc
CFLAGS = -O2

all: eight_neighbours.out 24_neighbours.out

eight_neighbours.out: eight_neighbours.c
	$(CC) $(CFLAGS) eight_neighbours.c -o eight_neighbours.out
24_neighbours.out: 24_neighbours.c
	$(CC) $(CFLAGS) 24_neighbours.c -o 24_neighbours.out

#clean:
#       rm *.o
